version: '2'
services:
  database:
    image: oracle/database:12.2.0.1-se2
    container_name: oracle
    restart: unless-stopped
    volumes:
      - /Users/jaz/Documents/oracle/oradata:/opt/oracle/oradata # persistent oracle database data.
    ports:
      - 1521:1521
      - 8081:8080
      - 5500:5500
